<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>
<body>
    <p>We've drafted these Terms of Service (which we simply call the "Terms") so that you'll know the rules that govern our relationship with you. Although we have tried our best to strip the legalese from the Terms, there are places where these Terms may still read like a traditional contract. There's a good reason for that: These Terms do indeed form a legally binding contract between you and LIVHUB. So please read them carefully.</p>
    <p>By using the Services, you agree to the Terms. Of course, if you don't agree with them, then don't use the Services.</p>
    <p>1. Who Can Use the Services</p>
    <p>No one under 18 is allowed to create an account or use the Services. We may offer additional Services with additional terms that may require you to be even older to use them. So please read all terms carefully.</p>
    <p>Your Content</p>
    <p>Personal Information that we automatically collect:</p>
    <p>You acknowledge and agree that you are solely responsible for any Content that you transmit or display through the Software or Services and that LIVHUB (and Apple or Google if you downloaded the Software from the App Store or Google Play) is not responsible to you or any third party in connection with any Content. You further agree to pay for all royalties, fees, and any other monies owing any person by reason of any of your Content. In addition, you represent and warrant that: (a) you are the creator and owner of or have the necessary rights to transmit or display the Content; and (b) the Content you transmit or you display does not and will not: (i) infringe, violate, or misappropriate any third-party right, including any copyright, trademark, patent, trade secret, moral right, privacy right, right of publicity, or any other intellectual property or proprietary right, or (ii) slander, defame, libel, or invade the right of privacy, publicity or other property rights of any other person. VIOLATORS OF THESE THIRD-PARTY RIGHTS MAY BE SUBJECT TO CRIMINAL AND CIVIL LIABILITY. LIVHUB RESERVES ALL RIGHTS AND REMEDIES AGAINST ANYONE WHO VIOLATES ANY OF THE PROVISIONS OF THIS TERMS OF USE</p>
    <p>How to Access Your Information</p>
    <p>You can access and modify the information you provided to us through your account. If you believe your information posted on LVEHUB is not authentic or accurate and can provide us with reasonable proof regarding this, you can require us via the contact information provided in this Privacy Policy to correct these unauthentic or inaccurate information and we will use reasonable efforts to honour your request; however, we may retain an archived copy of your information as required by law and/or for record keeping purposes. Once your account is closed or deleted, you will no longer have access to your message history, preferences or any other information associated with your use of our services. Even after you remove information from your account or profile, copies of that information may remain viewable elsewhere, to the extent it has been shared with others, it was otherwise distributed pursuant to your privacy settings, or it was copied or stored by other users. Additionally, we will retain your personal data even after you have closed your account if reasonably necessary to comply with our legal obligations (including law enforcement requests), meet regulatory requirements, resolve disputes, maintain security, prevent fraud and abuse, or enforce the Terms of Service. We will retain de-personalized information after your account has been closed. In some cases, we may not be able to update, amend or remove your personal information, in which case we will let you know why we are unable to do so, for example, certain requests may require disproportionate technical effort or extremely impractical, or are prohibited by law. Since LIVHUBLIVE will be used in multiple jurisdictions and we may not be possible to identify all the inconsistency between certain terms of this Privacy Policy and the applicable law in your jurisdiction, thus you agree to notify us once such inconsistency is identified by you. Under this circumstance we will take necessary methods to eliminate such inconsistency, including deleting these personal information improperly collected or used by us.</p>
    <p>Any questions about this Terms of Service should be addressed to livhubsupp01@gmail.com</p>
</html>